[package]
name = "ballista_python"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ballista = "44"
ballista-core = { version = "44", default-features = false }
ballista-executor = { version = "44", default-features = false }
ballista-scheduler = { version = "44", default-features = false }
datafusion = { version = "44", features = ["pyarrow"] }
datafusion-proto = { version = "44" }
log = "0.4"
tokio = { version = "1", features = ["full"] }

pyo3 = { version = "0.22", features = ["auto-initialize"] }
pyo3-log = "0.11"

prost = { version = "0.13.2" }
prost-types = { version = "0.13.2" }
async-trait = "0.1.88"

[dev-dependencies]
env_logger = "0.11"