name: Default Features

on:
  push:
    branches: [master, ci_*]
    paths-ignore:
      - "**.md"
      - "**.yaml"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**.yaml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # this one speeds up builds, they say
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      # make cargo format to fail first
      # before bringing other things, and spending time
      # compiling
      - name: Cargo Format Check
        run: cargo fmt --all --check --
      - name: Update Packages (apt-cache cache)
        run: sudo apt-get update
      - name: Install Required Libraries (using apt-get)
        run: sudo apt-get install -y protobuf-compiler
        # we use cache if format is correct
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Update gitconfig (Access to private repo)
        run: git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com".insteadOf ssh://git@github.com
      # - name: Cargo Compile (with tests)
      #   # should be faster than compiling tests again in
      #   # test phase
      #   # run: cargo test --no-run --locked --all-features
      #   run: cargo test --no-run --all-features
      - name: Cargo Run Tests
        run: cargo test  -- --nocapture --quiet
      # - name: Cargo Run Tests (Client Executor Feature Enabled)
      #   run: cargo test --features client_executor -- --nocapture --quiet
